id = "verilog"
name = "Verilog"
version = "0.0.3"
schema_version = 1
description = "Verilog and SystemVerilog support"
repository = "https://github.com/someone13574/zed-verilog-extension"
authors = ["Owen Law <owenlaw222@gmail.com>"]
themes = []
languages = ["languages/verilog"]

[lib]
kind = "Rust"
version = "0.0.6"

[grammars.verilog]
repository = "https://github.com/tree-sitter/tree-sitter-verilog"
rev = "075ebfc84543675f12e79a955f79d717772dcef3"

[language_servers.verible]
languages = ["Verilog", "SystemVerilog"]

[language_servers.verible.language_ids]

[language_servers.veridian]
languages = ["Verilog", "SystemVerilog"]

[language_servers.veridian.language_ids]
